problem/urls.py
from django.conf.urls import url
from problem.views import artifact1
from problem.views import artifact2
from problem.views import artifact3
from problem.views import artifact4
from problem.views import artifact5
from problem.views import artifact6
from problem.views import artifact7
from problem.views import artifact8
from problem.views import artifact9
from problem.views import artifact10
from problem.views import artifact11
from problem.views import artifact12
from problem.views import artifact13
from problem.views import anti1, anti2, anti3, case1, case2, case3, case4
from problem.views import problem_view
from problem.views import problem_write
from problem.views import problem_write_done
from problem.views import problem_answercheck
from problem.views import problem_download

urlpatterns = [
	url(r'^forensic/1/', artifact1, name='artifact1'),
	url(r'^forensic/2/', artifact2, name='artifact2'),
	url(r'^forensic/3/', artifact3, name='artifact3'),
	url(r'^forensic/4/', artifact4, name='artifact4'),
	url(r'^forensic/5/', artifact5, name='artifact5'),
	url(r'^forensic/6/', artifact6, name='artifact6'),
	url(r'^forensic/7/', artifact7, name='artifact7'),
	url(r'^forensic/8/', artifact8, name='artifact8'),
	url(r'^forensic/9/', artifact9, name='artifact9'),
	url(r'^forensic/10/', artifact10, name='artifact10'),
	url(r'^forensic/11/', artifact11, name='artifact11'),
	url(r'^forensic/12/', artifact12, name='artifact12'),
	url(r'^forensic/13/', artifact13, name='artifact13'),
	url(r'^antiforensic/1/', anti1, name='anti1'),
	url(r'^antiforensic/2/', anti2, name='anti2'),
	url(r'^antiforensic/3/', anti3, name='anti3'),
	url(r'^scenario/1/', case1, name='case1'),
	url(r'^scenario/2/', case2, name='case2'),
	url(r'^scenario/3/', case3, name='case3'),
	url(r'^scenario/4/', case4, name='case4'),
	url(r'^view/$', problem_view, name='problem_view'),
	url(r'^write/$', problem_write, name='problem_write'),
	url(r'^write_done/$', problem_write_done, name='problem_write_done'),
	url(r'^answer_check/$', problem_answercheck, name='problem_answercheck'),
	url(r'^download/$', problem_download, name='problem_download'),
]

testsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout

from testsite.views import HomeView

from testsite.views import user_login, login_check, register_page, register_done
from testsite.views import my_password_change, my_password_change_done
from testsite.views import intro, documents, problems, community, mypage, rank_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),

	url(r'^login/$', user_login, name='user_login'),
	url(r'^logout/$', logout, name='logout'),
	url(r'^login_check/$', login_check, name='login_check'),
	url(r'^register/$', register_page, name='register_page'),
	url(r'^register/done/$', register_done, name='register_done'),
	url(r'^mypage/password_change/$', my_password_change, name='password_change'),
	url(r'^mypage/password_change/done/$', my_password_change_done, name='password_change_done'),

	#url(r'^accounts/', include('django.contrib.auth.urls')),
	
	url(r'^$', HomeView.as_view(), name='home'),

	url(r'^intro/$', intro, name='intro'),
	# url(r'^documents/$', documents, name='documents'),
	url(r'^documents/', include('document.urls')),
	# url(r'^problems/$', problems, name='problems'),
	url(r'^problems/', include('problem.urls')),
	# url(r'^community/$', community, name='community'),
	url(r'^community/', include('community.urls')),
	url(r'^mypage/$', mypage, name='mypage'),
	url(r'^mypage/rank/$', rank_page, name='rank_page'),
]

problem/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Problem(models.Model):
	num = models.AutoField(primary_key=True)
	artifact = models.PositiveSmallIntegerField(null=True)
	title = models.CharField(max_length=50, blank=True)
	author = models.ForeignKey('auth.User')
	created_date = models.DateField(blank=True)
	level = models.PositiveSmallIntegerField(null=True)
	right_answer = models.CharField(max_length=100, null=True)
	submits = models.IntegerField(blank=True, null=True)
	corrects = models.IntegerField(blank=True, null=True)
	tags = models.CharField(max_length=200, null=True, blank=True)
	importance = models.PositiveSmallIntegerField(null=True)
	difficulty = models.PositiveSmallIntegerField(null=True)
	score = models.IntegerField(null=True)
	downfile = models.FileField(null=True, blank=True)
	content = models.TextField(null=True, blank=True)
	solve_user = models.CharField(max_length=200, null=True, blank=True)

	def __unicode__(self):
		return self.title

class Answerlog(models.Model):
	num = models.AutoField(primary_key=True)
	submitter = models.ForeignKey('auth.User')
	problem_num = models.IntegerField(null=True)
	problem_title = models.CharField(max_length=50, null=True)
	submit_answer = models.CharField(max_length=100, null=True)
	submit_date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.submit_answer

problem/views.py
import os
from django.shortcuts import render

# Create your views here.

from django.contrib.auth.models import User
from user_profile.models import UserProfile

from .models import Problem
from .models import Answerlog
from django.template import Context

from datetime import datetime
from django.http import HttpResponseRedirect, HttpResponse, StreamingHttpResponse

from django.contrib.auth.decorators import login_required
from ratelimit.decorators import ratelimit

from testsite.views import set_rank

class Counter:
	def __init__(self):
		self.count = 0
	
	def increment(self):
		self.count += 1
	
	def setzero(self):
		self.count = 0

def all_problem_test(request):
	problems = Problem.objects.all()
	tcounter = Counter()
	context = Context({'problems': problems, 'counter': tcounter, 'test': request})
	return render(request, '_all_problems.html', context)

@login_required(login_url='/login/')
def problem_view(request):
	state = False
	problem_num = request.GET['pnum']
	problem = Problem.objects.get(num=problem_num)
	if problem.tags is not None:
		problem_tags = problem.tags.split('#')[1:]
		for i in range(0, len(problem_tags)):
			problem_tags[i] = problem_tags[i].strip()
		blank_number = 5 - len(problem_tags)
	else:
		problem_tags = ""
		blank_number = 5
	if request.user.is_active:
		current_user = request.user.id
		user_level = UserProfile.objects.get(user_id=current_user).level
		right_problems = UserProfile.objects.get(user_id=current_user).right_problems.split(',')
		solve_user_list = []
		if problem.solve_user is None or problem.solve_user == '':
			solve_user_list.append("No one solved.")
		else:
			solve_users = problem.solve_user.split(',')
			for i in range(0, len(solve_users) - 1):
				solveuser = User.objects.get(id=solve_users[i])
				solve_user_list.append(solveuser.username)
		for i in range(0, len(right_problems) - 1):
			if int(right_problems[i]) == problem.num:
				state = True
				break
		context = Context({'problem': problem, 'test': request, 'user_level': user_level, 'state': state, 'problem_tags': problem_tags, 'blank': blank_number, 'solve_users': solve_user_list})
	else:
		context = Context({'problem': problem, 'test': request, 'problem_tags': problem_tags, 'blank': blank_number})
	return render(request, 'problem_view.html', context)

@login_required(login_url='/login/')
def problem_write(request):
	context = Context({})
	if not request.user.is_staff:
		return HttpResponseRedirect('/')
	return render(request, 'problem_write.html', context)

def problem_write_done(request):
	context = Context({})
	if not request.user.is_staff:
		return HttpResponseRedirect('/')
	if request.method == "GET":
		return render(request, 'problem_write.html', context)
	if request.method == "POST":
		if 'uploadfile' in request.FILES:
			problem = Problem(title = request.POST['title'], created_date = datetime.now(), content = request.POST['content'], author_id = request.user.id, level = request.POST['level'], artifact = request.POST['artifact'], right_answer = request.POST['right_answer'], corrects = 0, submits = 0, score = request.POST['score'], tags = request.POST['tags'], importance = request.POST['importance'], difficulty = request.POST['difficulty'], downfile = request.FILES['uploadfile'])
			problem.save()
		else:
			return render(request, 'problem_write.html', context)
	return render(request, 'problem_write_done.html', context)

@login_required(login_url='/login/')
def problem_download(request):
	if not request.user.is_active:
		return HttpResponseRedirect('/login_check/')
	problem_num = request.GET['pnum']
	problem = Problem.objects.get(num=problem_num)
	BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	fp = open(os.path.join(BASE_DIR, 'media')+'/'+str(problem.downfile), 'r')
	response = StreamingHttpResponse(fp, content_type='application/force-download')
	response['Content-Disposition'] = 'attachment; filename="%s"' % str(problem.downfile)
	return response

@ratelimit(key='ip', rate='1/30s', block=True)
def problem_answercheck(request):
	try:
		problem_num = request.GET['pnum']
		problem = Problem.objects.get(num=problem_num)
		answer = request.POST['answer']
	except:
		return HttpResponseRedirect('/')

	if answer is None:
		return HttpResponseRedirect('/')

	rights = UserProfile.objects.get(user_id=request.user.id).right_problems.split(',')

	for i in range(0, len(rights) - 1):
		if problem.num == int(rights[i]):
			context = Context({'problem_num': problem.num})
			return render(request, 'problem_solved.html', context)

	answerlog = Answerlog(submitter_id = request.user.id, submit_answer = answer, problem_num = problem.num, problem_title = problem.title)
	answerlog.save()
	UserProfile.objects.filter(user_id=request.user.id).update(last_submit = datetime.now())

	Problem.objects.filter(num=problem_num).update(submits = problem.submits + 1)

	if problem.right_answer.lower() == answer.lower():
		Problem.objects.filter(num=problem_num).update(corrects = problem.corrects + 1)
		if not request.user.is_staff:
			if problem.solve_user is None:
				Problem.objects.filter(num=problem_num).update(solve_user = str(request.user.id) + ',')
			else:
				Problem.objects.filter(num=problem_num).update(solve_user = str(problem.solve_user) + str(request.user.id) + ',')
		profile = UserProfile.objects.get(user_id=request.user.id)
		UserProfile.objects.filter(user_id=request.user.id).update(right_problems = profile.right_problems + str(problem_num) +',')
		if not request.user.is_staff:
			UserProfile.objects.filter(user_id=request.user.id).update(score = profile.score + problem.score)
		set_rank()
		state = True
	else:
		state = False

	context = Context({'problem_num': problem_num, 'state': state})
	return render(request, 'problem_answercheck.html', context)

def artifact1(request):
	orderby = request.GET.get('orderby')
	if orderby is None:
		orderby = 'title'

	if str(orderby) == "title":
		problems = Problem.objects.filter(artifact="1").order_by("title")
	elif str(orderby) == "rtitle":
		problems = Problem.objects.filter(artifact="1").order_by("-title")
	elif str(orderby) == "level":
		problems = Problem.objects.filter(artifact="1").order_by("level")
	elif str(orderby) == "rlevel":
		problems = Problem.objects.filter(artifact="1").order_by("-level")
	elif str(orderby) == "stats":
		problems = Problem.objects.raw('select * from problem_problem where artifact=1 order by CAST(corrects AS float) / (case when submits=0 then CAST(1 AS float) else CAST(submits AS float) end)')
	elif str(orderby) == "rstats":
		problems = Problem.objects.raw('select * from problem_problem where artifact=1 order by (CAST(corrects AS float) / (case when submits=0 then CAST(1 AS float) else CAST(submits AS float) end)) DESC')
	else:
		problems = Problem.objects.filter(artifact="1").order_by("title")
	tcounter = Counter()
	context = Context({'problems': problems, 'counter': tcounter, 'request': request})
	return render(request, 'artifact1/list.html', context)

def artifact2(request):
	orderby = request.GET.get('orderby')
	if orderby is None:
		orderby = 'title'

	if str(orderby) == "title":
		problems = Problem.objects.filter(artifact="2").order_by("title")
	elif str(orderby) == "rtitle":
		problems = Problem.objects.filter(artifact="2").order_by("-title")
	elif str(orderby) == "level":
		problems = Problem.objects.filter(artifact="2").order_by("level")
	elif str(orderby) == "rlevel":
		problems = Problem.objects.filter(artifact="2").order_by("-level")
	elif str(orderby) == "stats":
		problems = Problem.objects.raw('select * from problem_problem where artifact=2 order by CAST(corrects AS float) / (case when submits=0 then CAST(1 AS float) else CAST(submits AS float) end)')
	elif str(orderby) == "rstats":
		problems = Problem.objects.raw('select * from problem_problem where artifact=2 order by (CAST(corrects AS float) / (case when submits=0 then CAST(1 AS float) else CAST(submits AS float) end)) DESC')
	else:
		problems = Problem.objects.filter(artifact="2").order_by("title")
	tcounter = Counter()
	context = Context({'problems': problems, 'counter': tcounter, 'request': request})
	return render(request, 'artifact2/list.html', context)

def artifact3(request):
	orderby = request.GET.get('orderby')
	if orderby is None:
		orderby = 'title'

	if str(orderby) == "title":
		problems = Problem.objects.filter(artifact="3").order_by("title")
	elif str(orderby) == "rtitle":
		problems = Problem.objects.filter(artifact="3").order_by("-title")
	elif str(orderby) == "level":
		problems = Problem.objects.filter(artifact="3").order_by("level")
	elif str(orderby) == "rlevel":
		problems = Problem.objects.filter(artifact="3").order_by("-level")
	elif str(orderby) == "stats":
		problems = Problem.objects.raw('select * from problem_problem where artifact=3 order by CAST(corrects AS float) / (case when submits=0 then CAST(1 AS float) else CAST(submits AS float) end)')
	elif str(orderby) == "rstats":
		problems = Problem.objects.raw('select * from problem_problem where artifact=3 order by (CAST(corrects AS float) / (case when submits=0 then CAST(1 AS float) else CAST(submits AS float) end)) DESC')
	else:
		problems = Problem.objects.filter(artifact="3").order_by("title")
	tcounter = Counter()
	context = Context({'problems': problems, 'counter': tcounter, 'request': request})
	return render(request, 'artifact3/list.html', context)

def artifact4(request):
	orderby = request.GET.get('orderby')
	if orderby is None:
		orderby = 'title'

	if str(orderby) == "title":
		problems = Problem.objects.filter(artifact="4").order_by("title")
	elif str(orderby) == "rtitle":
		problems = Problem.objects.filter(artifact="4").order_by("-title")
	elif str(orderby) == "level":
		problems = Problem.objects.filter(artifact="4").order_by("level")
	elif str(orderby) == "rlevel":
		problems = Problem.objects.filter(artifact="4").order_by("-level")
	elif str(orderby) == "stats":

problem/templates/_all_problems_bak.html
{% extends 'base.html' %}

{% block content %}
<script type="text/javascript">
	$(document).ready(function() {
		$('nav .active').toggleClass("active");
		$('nav ul li:eq(3)').toggleClass("active");
	});
</script>
<div class="container content">
	<div class="menu col-md-2">
		<ul id="problem-menu" class="nav nav-pills nav-stacked">
			<li class="active"><a href="#artifact1">Artifact 1</a></li>
			<li><a href="#artifact2">Artifact 2</a></li>
			<li><a href="#artifact3">Artifact 3</a></li>
			<li><a href="#artifact4">Artifact 4</a></li>
			<li><a href="#artifact5">Artifact 5</a></li>
		</ul>
		<script type="text/javascript">
			var pmenu = $('#problem-menu a');
			for (var i = 0; i < pmenu.length; i++){
				$('#problem-menu a:eq('+i+')').click(function(e) {
					e.preventDefault();
					$(this).tab('show');
				});
			};
		</script>
	</div>
	<div class="problem-content col-md-10">
		<div class="tab-content">
			<div class="tab-pane fade in active" id="artifact1">
				<h1>Artifact 1</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 1 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact2">
				<h1>Artifact 2</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 2 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact3">
				<h1>Artifact 3</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 3 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact4">
				<h1>Artifact 4</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 4 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
			<div class="tab-pane fade" id="artifact5">
				<h1>Artifact 5</h1>
				<table class="table table-bordered">
					<thead>
						<tr>
							<td>#</td>
							<td>Problem</td>
							<td>Level</td>
							<td>stats</td>
						</tr>
					</thead>
					<div class="hidden">{{ counter.setzero }}</div>
					{% for problem in problems %}
						{% ifequal problem.artifact 5 %}
						<tr>
							<td class="problem_num col-md-1">{{ counter.count|add:"1" }}</td>
							<td class="col-md-8"><a href="#">{{ problem.title }}</a></td>
							<td>level{{ problem.level }}</td>
							<td></td>
							<div class="hidden">{{ counter.increment }}</div>
						</tr>
						{% endifequal %}
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
</div>
{% if test.user.is_superuser %}
	<div style="overflow: auto;">
		<input class="btn btn-info pull-right" type="button" value="Add Problem" onclick="location.href='/admin/problem/problem/add'"></input>
	</div>
{% endif %}

{% endblock content %}

problem/templates/problem_solved.html
<html>
	<head>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
	</head>
	<body>
		<div class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" id="hexit" class="close" data-dismiss="modal">×</button>
						<h4 class="modal-title">Already Solved!!</h4>
					</div>
					<div class="modal-body" style="text-align: center;">
						이미 푼 문제입니다.
					</div>
					<div class="modal-footer">
						<button type="button" id="exit" class="btn btn-default" data-dismiss="modal">닫기</button>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			$('div.modal').modal({
				backdrop: 'static',
				keyboard: false
			});
			$('#exit').focus();

			$('#hexit').click(function() {
				location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
			});
			$('#exit').click(function() {
				location.href = "{% url 'problem_view' %}?pnum={{ problem_num }}";
			});
		</script>
	</body>
</html>

problem/templates/problem_write.html
{% extends 'problem_menu.html' %}

{% block problem_content %}
<script type="text/javascript">
	{% if not request.user.is_staff %}
		alert('You don\'t have writing permission!!');
		$(location).attr("href", "{% url 'home' %}");
	{% endif %}
	$(document).ready(function() {
		$('#problem-menu > li:eq(0)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show(); 
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide(); 
		});

		$('#problem-menu > li:eq(1)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show(); 
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide(); 
		});

		$('#problem-menu > li:eq(2)').hover(function () {
			$(this).addClass("active");
			$(this).find("ul:first").show();
		}, function () {
			$(this).removeClass("active");
			$(this).find("ul:first").hide();
		});

		$('#addbutton').addClass("hidden");
		$('#id_submit').click(function() {
			var form = $('#write_problem');

			if(!$('input[name=title]').val()) {
				alert('Input title.');
				$('input[name=title]').focus();
				return;
			}

			if(!$('input[name=level]').val()) {
				alert('Input level.');
				$('input[name=level]').focus();
				return;
			}

			if(!$('input[name=score]').val()) {
				alert('Input score.');
				$('input[name=score]').focus();
				return;
			}

			if(!$('input[name=tags]').val()) {
				alert('Input tags.');
				$('input[name=tags]').focus();
				return;
			}

			if(!$('input[name=right_answer]').val()) {
				alert('Input right answer.');
				$('input[name=right_answer]').focus();
				return;
			}

			if(!$('textarea[name=content]').val()) {
				alert('Input content.');
				$('textarea[name=content]').focus();
				return;
			}

			form.submit();
		});

		$('#id_reset').click(function() {
			$('select[name=artifact] option:eq(0)').prop("selected", true);
			$('input[name=title]').val("");
			$('input[name=level]').val("");
			$('input[name=score]').val("");
			$('input[name=tags]').val("");
			$('select[name=importance] option:eq(0)').prop("selected", true);
			$('select[name=difficulty] option:eq(0)').prop("selected", true);
			$('input[name=right_answer]').val("");
			$('textarea[name=content]').val("");
		});
	});	
</script>
<div class="problem-content col-md-10">
	<form id="write_problem" class="form-horizontal" method="POST" action="{% url 'problem_write_done' %}" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="artifact" class="col-md-2 control-label">Artifact</label>
			<div class="col-md-10">
				<select name="artifact" class="form-control">
					<optgroup label="Artifact">
						<option value="1">Prefetch</option>
						<option value="2">Event Log</option>
						<option value="3">LNK</option>
						<option value="4">Shimcache</option>
						<option value="5">Memory Dump</option>
						<option value="6">Network</option>
						<option value="7">Thumbnail</option>
						<option value="8">VSS</option>
						<option value="9">Web Browser History</option>
						<option value="10">WER & Crash Dump</option>
						<option value="11">MFT</option>
						<option value="12">Fils System</option>
						<option value="13">Registry</option>
					</optgroup>
					<optgroup label="Anti-Forensic">
						<option value="14">Steganography</option>
						<option value="15">Hidden File</option>
						<option value="16">File Delete</option>
					</optgroup>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="id_title" class="col-md-2 control-label">Title</label>
			<div class="col-md-10">
				<input type="text" id="id_title" class="form-control" name="title" maxlength="50" placeholder="Title">
			</div>
		</div>
		<div class="form-group">
			<label for="id_author" class="col-md-2 control-label">Author</label>
			<div class="col-md-10">
				<input type="text" id="id_author" class="form-control" name="author" value="{{ request.user.username }}" disabled>
			</div>
		</div>
		<div class="form-group">
			<label for="id_level" class="col-md-2 control-label">Level</label>
			<div class="col-md-4">
				<input type="text" id="id_level" class="form-control" name="level" placeholder="Level">
			</div>
			<label for="id_score" class="col-md-2 control-label">Score</label>
			<div class="col-md-4">
				<input type="text" id="id_score" class="form-control" name="score" placeholder="Score">
			</div>
		</div>
		<div class="form-group">
			<label for="id_tags" class="col-md-2 control-label">Tags</label>
			<div class="col-md-10">
				<input type="text" id="id_tags" class="form-control" name="tags" placeholder="Tags">
			</div>
		</div>
		<div class="form-group">
			<label for="id_importance" class="col-md-2 control-label">Importance</label>
			<div class="col-md-4">
				<select name="importance" class="form-control">
					<option value="2">High</option>
					<option value="1">Middle</option>
					<option value="0">Low</option>
				</select>
			</div>
			<label for="id_difficulty" class="col-md-2 control-label">Difficulty</label>
			<div class="col-md-4">
				<select name="difficulty" class="form-control">
					<option value="2">High</option>
					<option value="1">Middle</option>
					<option value="0">Low</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label for="id_right_answer" class="col-md-2 control-label">Right Answer</label>
			<div class="col-md-10">
				<input type="text" id="id_right_answer" class="form-control" name="right_answer" placeholder="Right Answer">
			</div>
		</div>
		<div class="form-group">
			<label for="id_file" class="col-md-2 control-label">Upload File</label>
			<div class="col-md-10">
				<input type="file" id="id_file" class="form-control" name="uploadfile">
			</div>
		</div>
		<div class="form-group">
			<label for="id_content" class="col-md-2 control-label">Content</label>
			<div class="col-md-10">
				<textarea id="id_content" class="form-control" name="content" rows="10"></textarea>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-12">
				<input type="button" id="id_submit" class="btn btn-default pull-right" value="Submit">
				<input type="button" id="id_reset" class="btn btn-default pull-right" value="Reset">
			</div>
		</div>
	</form>
</div>
{% endblock problem_content %}

problem/templates/problem_write_done.html
<script type="text/javascript">
	alert('Adding Problem Success');
	location.href="{% url 'artifact1' %}"
</script>